name: CI/CD

on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Terraform
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: "1.1.4"

      - name: Cache Terraform modules
        uses: actions/cache@v4
        with:
          path: .terraform/
          key: terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: terraform-

      - run: terraform init
      - run: terraform fmt -check
      - run: terraform validate -no-color

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install PHP dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit --testdox || echo "No tests defined"

  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Deploy (placeholder)
        run: echo "🔔 You can add your PHP deployment logic here"
